# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic Publish'

on:
  # Event for the workflow to run on
  push:
    branches:
      - 'main' # Replace with the branch you want to deploy from

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken,
          projectToken: ${{ secrets.CHROMATIC_CHROMATIC_UI_TOKEN }}
          token: ${{ secrets.CUPCAKE_UI_SECRET }}
